"""
Per-game metadata for the frontend.
This is purely descriptive — all financial logic lives in the contracts.
"""

GAME_CONFIGS = {
    "dice": {
        "key": "dice",
        "name": "Dice Over/Under",
        "tagline": "Roll the block. Beat the dead zone.",
        "min_bet_eth": 0.0001,
        "max_bet_eth": 10.0,
        "default_bet_eth": 0.01,
        "chip_values": [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
        "bet_types": {
            0: {
                "label": "OVER",
                "description": "Wins when the roll is 51-99",
                "color": "#00d2ff",
                "win_condition": "result > 50",
            },
            1: {
                "label": "UNDER",
                "description": "Wins when the roll is 0-49",
                "color": "#ff5e78",
                "win_condition": "result < 50",
            },
        },
        "dead_zone": 50,
        "dead_zone_label": "DEAD ZONE",
        "outcome_max": 99,
    },
    "color-duel": {
        "key": "color-duel",
        "name": "Color Duel",
        "tagline": "Red vs Green vs Blue. Pick the winning hue.",
        "min_bet_eth": 0.0001,
        "max_bet_eth": 10.0,
        "default_bet_eth": 0.01,
        "chip_values": [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
        "bet_types": {
            0: {
                "label": "RED",
                "description": "Wins when the duel resolves RED",
                "color": "#ff5e78",
                "win_condition": "result == 0",
            },
            1: {
                "label": "GREEN",
                "description": "Wins when the duel resolves GREEN",
                "color": "#00e0a0",
                "win_condition": "result == 1",
            },
            2: {
                "label": "BLUE",
                "description": "Wins when the duel resolves BLUE",
                "color": "#00d2ff",
                "win_condition": "result == 2",
            },
        },
        "outcome_max": 2,
    },
    "crash": {
        "key": "crash",
        "name": "Crash / Rocket",
        "tagline": "Pick a tier. Survive the crash.",
        "min_bet_eth": 0.0001,
        "max_bet_eth": 10.0,
        "default_bet_eth": 0.01,
        "chip_values": [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
        "bet_types": {
            0: {
                "label": "1.5X",
                "description": "Wins if crash point is 1.50x or higher",
                "color": "#00d2ff",
                "win_condition": "crash >= 150",
            },
            1: {
                "label": "2X",
                "description": "Wins if crash point is 2.00x or higher",
                "color": "#00e0a0",
                "win_condition": "crash >= 200",
            },
            2: {
                "label": "3X",
                "description": "Wins if crash point is 3.00x or higher",
                "color": "#ffd166",
                "win_condition": "crash >= 300",
            },
            3: {
                "label": "5X",
                "description": "Wins if crash point is 5.00x or higher",
                "color": "#ff9f43",
                "win_condition": "crash >= 500",
            },
            4: {
                "label": "10X",
                "description": "Wins if crash point is 10.00x or higher",
                "color": "#ff5e78",
                "win_condition": "crash >= 1000",
            },
        },
        "outcome_max": 10000,
    },
    "plinko": {
        "key": "plinko",
        "name": "Plinko",
        "tagline": "Drop the ball. Pick the landing zone.",
        "min_bet_eth": 0.0001,
        "max_bet_eth": 10.0,
        "default_bet_eth": 0.01,
        "chip_values": [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
        "bet_types": {
            0: {
                "label": "ZONE",
                "description": "Wins if the ball lands in the selected zone",
                "color": "#a78bfa",
                "win_condition": "zone == betValue",
            },
        },
        "zones": 13,
        "outcome_max": 12,
    },
    "roulette": {
        "key": "roulette",
        "name": "Roulette",
        "tagline": "European parimutuel wheel. Pick a color, range, or exact number.",
        "min_bet_eth": 0.0001,
        "max_bet_eth": 10.0,
        "default_bet_eth": 0.01,
        "chip_values": [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
        "bet_types": {
            0: {
                "label": "RED",
                "description": "Wins when the ball lands on a red number (1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36)",
                "color": "#ff5e78",
                "win_condition": "red number",
            },
            1: {
                "label": "BLACK",
                "description": "Wins when the ball lands on a black number",
                "color": "#2b2b2b",
                "win_condition": "black number",
            },
            2: {
                "label": "EVEN",
                "description": "Wins on 2-36 even (excludes 0)",
                "color": "#a78bfa",
                "win_condition": "even number",
            },
            3: {
                "label": "ODD",
                "description": "Wins on 1-35 odd",
                "color": "#ffd166",
                "win_condition": "odd number",
            },
            4: {
                "label": "HIGH",
                "description": "Wins on 19-36",
                "color": "#00d2ff",
                "win_condition": "19-36",
            },
            5: {
                "label": "LOW",
                "description": "Wins on 1-18",
                "color": "#00e0a0",
                "win_condition": "1-18",
            },
            6: {
                "label": "NUMBER",
                "description": "Wins only on the exact number you pick (0-36)",
                "color": "#ff9f43",
                "win_condition": "exact number",
            },
        },
        "single_number_bet_type": 6,
        "outcome_max": 36,
    },
    "coin-flip": {
        "key": "coin-flip",
        "name": "Coin Flip Streak",
        "tagline": "How many heads in a row before the first tails?",
        "min_bet_eth": 0.0001,
        "max_bet_eth": 10.0,
        "default_bet_eth": 0.01,
        "chip_values": [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
        "bet_types": {
            0: {
                "label": "0 HEADS",
                "description": "Wins if the first flip is tails",
                "color": "#ff5e78",
                "win_condition": "streak == 0",
            },
            1: {
                "label": "1 HEAD",
                "description": "Wins if the first flip is heads and second is tails",
                "color": "#ffd166",
                "win_condition": "streak == 1",
            },
            2: {
                "label": "2 HEADS",
                "description": "Wins if the first two flips are heads",
                "color": "#00e0a0",
                "win_condition": "streak == 2",
            },
            3: {
                "label": "3 HEADS",
                "description": "Wins if the first three flips are heads",
                "color": "#00d2ff",
                "win_condition": "streak == 3",
            },
            4: {
                "label": "4 HEADS",
                "description": "Wins if the first four flips are heads",
                "color": "#a78bfa",
                "win_condition": "streak == 4",
            },
            5: {
                "label": "5 HEADS",
                "description": "Wins if the first five flips are heads",
                "color": "#ff9f43",
                "win_condition": "streak == 5",
            },
            6: {
                "label": "6+ HEADS",
                "description": "Wins if six or more consecutive heads",
                "color": "#ffffff",
                "win_condition": "streak >= 6",
            },
        },
        "outcome_max": 20,
    },
    "slots": {
        "key": "slots",
        "name": "Slots",
        "tagline": "Three reels. Match symbols to win.",
        "min_bet_eth": 0.0001,
        "max_bet_eth": 10.0,
        "default_bet_eth": 0.01,
        "chip_values": [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
        "bet_types": {
            0: {
                "label": "EXACT TRIPLE",
                "description": "All three reels match the chosen symbol",
                "color": "#ff9f43",
                "win_condition": "s1==s2==s3==symbol",
            },
            1: {
                "label": "ANY TRIPLE",
                "description": "All three reels match, any symbol",
                "color": "#ffd166",
                "win_condition": "s1==s2==s3",
            },
            2: {
                "label": "ANY PAIR",
                "description": "Any two reels match the chosen symbol",
                "color": "#00d2ff",
                "win_condition": "two match symbol",
            },
            3: {
                "label": "FIRST SYMBOL",
                "description": "The first reel matches the chosen symbol",
                "color": "#00e0a0",
                "win_condition": "s1==symbol",
            },
        },
        "symbols": 8,
        "symbol_names": ["0", "1", "2", "3", "4", "5", "6", "7"],
        "outcome_max": 0x777,
    },
    "horse-race": {
        "key": "horse-race",
        "name": "Horse Race",
        "tagline": "Six virtual horses. Pick a finisher.",
        "min_bet_eth": 0.0001,
        "max_bet_eth": 10.0,
        "default_bet_eth": 0.01,
        "chip_values": [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
        "bet_types": {
            0: {
                "label": "WIN",
                "description": "Horse must finish 1st",
                "color": "#ff5e78",
                "win_condition": "horse == 1st",
            },
            1: {
                "label": "PLACE",
                "description": "Horse must finish 1st or 2nd",
                "color": "#ffd166",
                "win_condition": "horse in top 2",
            },
            2: {
                "label": "SHOW",
                "description": "Horse must finish in top 3",
                "color": "#00d2ff",
                "win_condition": "horse in top 3",
            },
            3: {
                "label": "EXACTA",
                "description": "Pick exact 1st and 2nd horses in order",
                "color": "#00e0a0",
                "win_condition": "top 2 in exact order",
            },
        },
        "horses": 6,
        "horse_names": ["0", "1", "2", "3", "4", "5"],
        "outcome_max": 0x55555,
    },
    "keno": {
        "key": "keno",
        "name": "Keno",
        "tagline": "Pick 5 numbers. Match 5, 4, 3, or none to win.",
        "min_bet_eth": 0.0001,
        "max_bet_eth": 10.0,
        "default_bet_eth": 0.01,
        "chip_values": [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
        "bet_types": {
            0: {
                "label": "MATCH 5",
                "description": "All 5 of your picks are drawn",
                "color": "#ff9f43",
                "win_condition": "matches == 5",
            },
            1: {
                "label": "MATCH 4",
                "description": "Exactly 4 of your picks are drawn",
                "color": "#ffd166",
                "win_condition": "matches == 4",
            },
            2: {
                "label": "MATCH 3",
                "description": "Exactly 3 of your picks are drawn",
                "color": "#00d2ff",
                "win_condition": "matches == 3",
            },
            3: {
                "label": "MATCH 0",
                "description": "None of your picks are drawn",
                "color": "#00e0a0",
                "win_condition": "matches == 0",
            },
        },
        "numbers": 40,
        "pick_count": 5,
        "outcome_max": 0xFFFFFFFFFF,
    },
    "block-bingo": {
        "key": "block-bingo",
        "name": "Block Bingo",
        "tagline": "Five blocks draw your numbers. Complete a line to win.",
        "min_bet_eth": 0.0001,
        "max_bet_eth": 10.0,
        "default_bet_eth": 0.01,
        "chip_values": [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
        "bet_types": {
            0: {
                "label": "BINGO",
                "description": "Your generated card completes any row, column, or diagonal",
                "color": "#a78bfa",
                "win_condition": "card has bingo",
            },
        },
        "card_size": 5,
        "numbers": 75,
        "outcome_max": 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,
    },
    "minefield": {
        "key": "minefield",
        "name": "Minefield",
        "tagline": "5 mines hide on a 5×5 grid. Pick safe or mine.",
        "min_bet_eth": 0.0001,
        "max_bet_eth": 10.0,
        "default_bet_eth": 0.01,
        "chip_values": [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
        "bet_types": {
            0: {
                "label": "SAFE",
                "description": "The chosen cell is NOT a mine",
                "color": "#00e0a0",
                "win_condition": "cell is safe",
            },
            1: {
                "label": "MINE",
                "description": "The chosen cell IS a mine",
                "color": "#ff5e78",
                "win_condition": "cell is mine",
            },
        },
        "grid_size": 25,
        "mines": 5,
        "outcome_max": 0x1FFFFFF,
    },
}
